// GENERATED by scripts/build-connector.mjs.
/** The Apps Script the coach pastes (sheets-connector/Code.gs). */
export declare const CONNECTOR_SOURCE: string;
/** Bumped with `const VERSION` in Code.gs; the connector reports it on ping. */
export declare const CONNECTOR_VERSION: number;
