/**
 * Geneva Tennis match library: the one entry point for the app (the types are in index.d.ts).
 * The tracker build does NOT use this file; it inlines score, stats, trends, xlsx and sheets.
 * connectorSource is generated by scripts/build-connector.mjs from sheets-connector/Code.gs.
 */
export { FORMATS, MatchScore } from './score.js';
export { computeStats, fmtRatio, pct, gameGroups } from './stats.js';
export { detectTrends } from './trends.js';
export { buildXlsx, bytesToBase64, toCSV, toTSV, plainRows, utf8Bytes } from './xlsx.js';
export { pointLogRows, shotRows, summaryRows, matchWorkbook, matchFileName } from './sheets.js';
export { CONNECTOR_SOURCE, CONNECTOR_VERSION } from './connectorSource.js';
